SELECT * FROM LAB06
UPDATE LAB06 SET FORMATNUMBER= '+90 ('+SUBSTRING(TELNR,2,3)+') '+SUBSTRING(TELNR,4,3)+' '+SUBSTRING(TELNR,8,2)+' '+SUBSTRING(TELNR,10,2) 

ALTER TABLE LAB06 ADD FORMATNUMBER VARCHAR(20)/*COLUMN ADDED