select	 CATEGORY1+REPLICATE(0,15-LEN(ITEMCODE)-LEN(CATEGORY1))+ITEMCODE AS SMARTCODE from lab02
--ABOVE VIRTUAL QUERY
SELECT *FROM LAB02--OUR TABLE
ALTER TABLE LAB02 ADD SMARTCODE VARCHAR(16)--ADDED NEW COLUMN 
UPDATE LAB02 SET SMARTCODE= CATEGORY1+REPLICATE(0,15-LEN(ITEMCODE)-LEN(CATEGORY1))+ITEMCODE-- AND UPDATED NEW COLUMN